name: flemozi
description: A powerful emoji picker
publish_to: "none"
version: 0.2.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  fuzzywuzzy: ^1.1.6
  google_fonts: ^5.1.0
  http: ^1.1.0
  hooks_riverpod: ^2.3.10
  riverpod: ^2.3.10
  window_manager: ^0.3.6
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  launch_at_startup: ^0.2.2
  package_info_plus: ^4.1.0
  alfred: ^1.1.1
  shared_preferences: ^2.2.1
  system_theme: ^2.3.1
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.14
  fl_query: ^1.0.0-alpha.3
  fl_query_hooks: ^1.0.0-alpha.3
  giphy_api_client: ^0.1.3
  json_annotation: ^4.8.1
  visibility_detector: ^0.4.0+2
  flutter_cache_manager: ^3.3.1
  path: ^1.8.3
  easy_debounce: ^2.0.3
  uuid: ^3.0.7
  shimmer: ^3.0.0
  hive_flutter: ^1.1.0
  auto_size_text: ^3.0.0
  path_provider: ^2.1.1
  super_clipboard: ^0.6.4
  super_hot_key: ^0.6.4
  super_keyboard_layout: ^0.6.4
  envied: ^0.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  melos: ^3.1.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_launcher_icons: ^0.13.1
  html: ^0.15.4
  pub_api_client: ^2.6.0

dependency_overrides:
  collection: ^1.18.0
  http: ^1.1.0
  flutter_hooks: ^0.20.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/twemoji/

flutter_icons:
  android: false
  ios: false
  image_path: "assets/logo.png"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
