name: flemozi
description: A powerful emoji picker
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  fuzzywuzzy: ^0.2.0
  google_fonts: ^4.0.3
  hooks_riverpod: ^2.1.3
  http: ^0.13.5
  riverpod: ^2.1.3
  window_manager: ^0.3.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  hotkey_manager:
    git:
      url: https://github.com/leanflutter/hotkey_manager.git
      ref: 604523dd6edfb54e643f577512ea698c8debb96d
  launch_at_startup: ^0.2.2
  package_info_plus: ^3.0.3
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true    
  assets:
    - assets/
    - assets/twemoji/