display_name: Flemozi
package_name: flemozi

maintainer:
  name: Kingkor Roy Tirtho
  email: krtirtho@gmail.com

priority: optional
section: x11
installed_size: 24400

dependencies:
  - keybinder-3.0

essential: false
icon: assets/logo.png

keywords:
  - Emoji
  - Clipboard

generic_name: Emoji Picker
categories:
  - Utility

startup_notify: true