app_id: FBCAB0B1-8171-40FA-B28E-234B17743354
publisher: KRTirtho, OSS
publisher_url: https://github.com/KRTirtho/flemozi
display_name: Flemozi
create_desktop_icon: true
install_dir_name: Flemozi
locales:
  - en
